# .github/workflows/test.yml

name: Sync and Format

on: push

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev

      - name: Config git.
        run: |
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'

      - name: Sync setup.py and check if it did anything.
        id: check1
        run: |
          pipenv run pipenv-setup sync
          git diff --exit-code setup.py; echo ::set-output name=key::$?

      - name: Commit setup.py .
        if: failure() && steps.check1.outputs.key == 1
        run: git commit -am "Auto setup.py syncing."

      - name: Check for unformatted python code.
        id: check2
        if: always()
        run: |
          pipenv run black --check -l 80 .; echo ::set-output name=key::$?

      - name: Format and commit python files.
        if: failure() && steps.check2.outputs.key == 1
        run: |
          pipenv run black -l 80 .
          git commit -am "Auto black formatting"

      - name: Push changes.
        if: always()
        run: git push
